apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubview
  labels:
    app: pubview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubview
  template:
    metadata:
      labels:
        app: pubview
    spec:
      containers:
        - name: pubview
          image: username/pubview:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5